### ISSUE TITLE
Build Skeleton of Liquid Modal

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#655] opened 2024-06-05 21:42 UTC
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by Keegnan** [comment] 2024-07-03 21:59
Was a duplicate of a previous ticket.

**Closed** 2024-07-03 21:58 UTC
Labels: User Story, Duplicate
